version: '3.7'

services:
  flask_server:
    build: .
    ports:
      - "5462:5462"
    volumes:
      - /home/ubuntu/data:/data
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "443:443"   # Expose port 443 for HTTPS
      - "80:80"     # Optionally expose port 80 for HTTP (redirect to HTTPS)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - flask_server
    restart: always
