
services:
  # blaze:
  #   image: docker.verbis.dkfz.de/cache/samply/blaze:latest
  #   container_name: bridgehead-leme-blaze
  #   environment:
  #     BASE_URL: "http://bridgehead-leme-blaze:8080"
  #     JAVA_TOOL_OPTIONS: "-Xmx${BLAZE_MEMORY_CAP:-4096}m"
  #     DB_RESOURCE_CACHE_SIZE: ${BLAZE_RESOURCE_CACHE_CAP:-2500000}
  #     DB_BLOCK_CACHE_SIZE: $BLAZE_MEMORY_CAP
  #     ENFORCE_REFERENTIAL_INTEGRITY: "false"
  #   volumes:
  #     - "blaze-data:/app/data"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.blaze_leme.rule=PathPrefix(`/leme-localdatamanagement`)"
  #     - "traefik.http.middlewares.leme_b_strip.stripprefix.prefixes=/leme-localdatamanagement"
  #     - "traefik.http.services.blaze_leme.loadbalancer.server.port=8080"
  #     - "traefik.http.routers.blaze_leme.middlewares=leme_b_strip,auth"
  #     - "traefik.http.routers.blaze_leme.tls=true"

  # focus:
  #   image: docker.verbis.dkfz.de/cache/samply/focus:0.4.4
  #   container_name: bridgehead-focus
  #   environment:
  #     API_KEY: ${FOCUS_BEAM_SECRET_SHORT}
  #     BEAM_APP_ID_LONG: focus.${PROXY_ID}
  #     PROXY_ID: ${PROXY_ID}
  #     BLAZE_URL: "http://bridgehead-leme-blaze:8080/fhir/"
  #     BEAM_PROXY_URL: http://beam-proxy:8081
  #     RETRY_COUNT: ${FOCUS_RETRY_COUNT}
  #     EPSILON: 0.28
  #   depends_on:
  #     - "beam-proxy"
  #     - "blaze"

  beam-proxy:
    image: samply/beam-proxy:develop
    container_name: bridgehead-beam-proxy
    environment:
      BROKER_URL: ${BROKER_URL}
      PROXY_ID: ${PROXY_ID}
      APP_focus_KEY: ${FOCUS_BEAM_SECRET_SHORT}
      APP_sender_KEY: testbridgehead                  # GLEICH WIE IN file-sender
      APP_receiver_KEY: testbridgehead                # GLEICH WIE IN file-receiver
      PRIVKEY_FILE: /run/secrets/proxy.pem
      ALL_PROXY: http://forward_proxy:3128
      TLS_CA_CERTIFICATES_DIR: /conf/trusted-ca-certs
      ROOTCERT_FILE: /conf/root.crt.pem
    secrets:
      - proxy.pem
    depends_on:
      - "forward_proxy"
    volumes:
      - /etc/bridgehead/trusted-ca-certs:/conf/trusted-ca-certs:ro
      - /srv/docker/bridgehead/leme/root.crt.pem:/conf/root.crt.pem:ro

  file-sender:
    image: samply/beam-file:task-based-files-server
    command: ["server"]
    environment:
      BEAM_URL: http://beam-proxy:8081
      BEAM_SECRET: testbridgehead                     # hinzufügen in beam-proxy
      BEAM_ID: sender.${PROXY_ID}
      BIND_ADDR: 0.0.0.0:8080
      #API_KEY: testbridgehead_api_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-sender.rule=PathPrefix(`/send`)"              # Füge Pfad ein schauen wie ID
      # - "traefik.http.middlewares.leme_b_strip.stripprefix.prefixes=/send"
      - "traefik.http.services.file-sender.loadbalancer.server.port=8080"
      - "traefik.http.routers.file-sender.tls=true"
      - "traefik.http.routers.file-sender.middlewares=auth"

  file-receiver:
    image: samply/beam-file:task-based-files-server
    command: ["receive", "save", "-o", "/data", "-p", "%f_%t_%n"]         # statt "send" auch "callback" zum weitersenden zu bsp. FASTAPI order Experss Server
    environment:
      BEAM_URL: http://beam-proxy:8081
      BEAM_SECRET: testbridgehead                     # hinzufügen in beam-proxy
      BEAM_ID: receiver.${PROXY_ID}
    volumes:
      - /home/ubuntu/data:/data

  file-watcher:
    image: file-watcher
    build:
      context: /srv/docker/bridgehead/standort_preprocessing
      dockerfile: Dockerfile
    volumes:
      - /home/ubuntu/data:/data
    environment:
      DIRECTORY_TO_WATCH: /data
      POST_URL: https://81.89.199.152/send/receiver.UniMannheim
      USERNAME: leme
      PASSWORD: ab89cb45b2a44142a474653db22d32d0



# volumes:
#   blaze-data:

secrets:
  proxy.pem:
    file: /etc/bridgehead/pki/${SITE_ID}.priv.pem
